/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nigelgrange_jrncryptor_JRNCryptor */

#ifndef _Included_com_nigelgrange_jrncryptor_JRNCryptor
#define _Included_com_nigelgrange_jrncryptor_JRNCryptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nigelgrange_jrncryptor_JRNCryptor
 * Method:    encryptWithPassword
 * Signature: ([BLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_nigelgrange_jrncryptor_JRNCryptor_encryptWithPassword
  (JNIEnv *, jobject, jbyteArray, jstring);

/*
 * Class:     com_nigelgrange_jrncryptor_JRNCryptor
 * Method:    decryptWithPassword
 * Signature: ([BLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_nigelgrange_jrncryptor_JRNCryptor_decryptWithPassword
  (JNIEnv *, jobject, jbyteArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
